<a href="https://colab.research.google.com/github/Sharaiz333/AI/blob/main/57288_Lab06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

goal = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,0]])

start = np.array([[1,2,3],
                  [4,0,6],
                  [7,5,8]])

def heuristic(state):
    h = np.sum((state != goal) & (state != 0))
    return h

def find_zero(state):
    pos = np.argwhere(state == 0)[0]
    return pos[0], pos[1]

def get_neighbors(state):
    neighbors = []
    x,y = find_zero(state)

    moves = [(0,1),(1,0),(0,-1),(-1,0)]

    for dx,dy in moves:
        nx,ny = x+dx, y+dy
        if 0 <= nx < 3 and 0 <= ny < 3:
            new_state = state.copy()
            new_state[x,y], new_state[nx,ny] = new_state[nx,ny], new_state[x,y]
            neighbors.append(new_state)

    return neighbors

def a_star(start):
    pq = [(heuristic(start), start)]
    visited = []

    while pq:

        costs = np.array([item[0] for item in pq])
        idx = np.argmin(costs)

        cost, state = pq.pop(idx)

        if np.array_equal(state, goal):
            print("Goal Reached!")
            print(state)
            return

        visited.append(state.tolist())

        for neighbor in get_neighbors(state):
            if neighbor.tolist() not in visited:
                f = heuristic(neighbor)
                pq.append((f, neighbor))

a_star(start)

Goal Reached!
[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [ ]:
import heapq

def a_star_graph(graph, heuristics, start, goal):

    open_list = []
    heapq.heappush(open_list, (0, start))

    g_cost = {node: float('inf') for node in graph}
    g_cost[start] = 0

    parent = {start: None}

    while open_list:
        f, current = heapq.heappop(open_list)

        if current == goal:
            print("Goal Reached!")
            path = []
            while current:
                path.append(current)
                current = parent[current]
            path.reverse()

            print("Shortest Path:", " -> ".join(path))
            print("Total Cost:", g_cost[goal])
            return

        for neighbor, cost in graph[current]:
            new_g = g_cost[current] + cost

            if new_g < g_cost[neighbor]:
                g_cost[neighbor] = new_g
                f_new = new_g + heuristics[neighbor]
                heapq.heappush(open_list, (f_new, neighbor))
                parent[neighbor] = current

    print("No Path Found")


# Example Graph
graph = {
    'A': [('B', 1), ('C', 3)],
    'B': [('D', 3), ('E', 1)],
    'C': [('F', 5)],
    'D': [],
    'E': [('F', 1)],
    'F': []
}

heuristics = {
    'A': 6,
    'B': 4,
    'C': 4,
    'D': 2,
    'E': 1,
    'F': 0
}

a_star_graph(graph, heuristics, 'A', 'F')

Goal Reached!
Shortest Path: A -> B -> E -> F
Total Cost: 3
