<a href="https://colab.research.google.com/github/Sharaiz333/AI/blob/main/Sharaiz_57288_Lab03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Check NumPy Version

In [ ]:
import numpy as np
print(np.__version__)


2.0.2


# Create 1-D Array

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


# Create 2-D Array

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)


[[1 2 3]
 [4 5 6]]


# Array Attributes (ndim, shape, size)

In [ ]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])

print("Dimensions:", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)


Dimensions: 2
Shape: (2, 3)
Size: 6


# Basic Array Operations

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Multiplication:", a * b)


Addition: [5 7 9]
Multiplication: [ 4 10 18]


# Array Creation Functions

# arange()

In [ ]:
import numpy as np
arr = np.arange(0, 10, 2)
print(arr)


[0 2 4 6 8]


# eye()

In [ ]:
import numpy as np
arr = np.eye(3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# ones()

In [ ]:
import numpy as np
arr = np.ones((2, 3))
print(arr)


[[1. 1. 1.]
 [1. 1. 1.]]


# zeros()

In [ ]:
import numpy as np
arr = np.zeros((2, 3))
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]]


# full()

In [ ]:
import numpy as np
arr = np.full((2, 3), 7)
print(arr)


[[7 7 7]
 [7 7 7]]


# Change Data Type

In [ ]:
import numpy as np

A = np.array([1, 2, 3])
A = A.astype(np.float64)

print(A)
print(A.dtype)


[1. 2. 3.]
float64


#0-D Array

In [ ]:
import numpy as np
arr = np.array(10)
print(arr)
print(arr.ndim)


10
0


# 1-D Array

In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr.ndim)


1


# 2-D Array

In [ ]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(arr.ndim)


2


# 3-D Array

In [ ]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]]])
print(arr.ndim)


3


# Array Indexing
# 1-D Indexing

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[2])


30


# 2-D Indexing

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1, 2])


6


# Negative Indexing

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[-1])


40


# Array Slicing
# Basic Slicing

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])


[2 3 4]


# Step Sliciing

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[0:5:2])


[1 3 5]


# 2-D Slicing

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0:2, 1:3])


[[2 3]
 [5 6]]


# Array Shape

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)


(2, 3)


# Reshape Array

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = arr.reshape(2,3)
print(newarr)


[[1 2 3]
 [4 5 6]]


# Flatten Array

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
flat = arr.reshape(-1)
print(flat)


[1 2 3 4 5 6]


# Copy vs View
# Copy

In [ ]:
import numpy as np
arr = np.array([1,2,3])
x = arr.copy()
arr[0] = 10
print(arr)
print(x)


[10  2  3]
[1 2 3]


# View

In [ ]:
import numpy as np
arr = np.array([1,2,3])
x = arr.view()
arr[0] = 10
print(arr)
print(x)


[10  2  3]
[10  2  3]


# Array Iteration
# 1-D

In [ ]:
import numpy as np
arr = np.array([1,2,3])
for x in arr:
    print(x)


1
2
3


# 2-D

In [ ]:
import numpy as np
arr = np.array([[1,2],[3,4]])
for row in arr:
    for element in row:
        print(element)


1
2
3
4


# Using nditer()

In [ ]:
import numpy as np
arr = np.array([[1,2],[3,4]])
for x in np.nditer(arr):
    print(x)


1
2
3
4


# Joining Arrays

# concatenate()

In [ ]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.concatenate((arr1, arr2))
print(newarr)


[1 2 3 4 5 6]


# stack()

In [ ]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.stack((arr1, arr2), axis=1)
print(newarr)


[[1 4]
 [2 5]
 [3 6]]


# Splitting Arrays

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 3)
print(newarr)


[array([1, 2]), array([3, 4]), array([5, 6])]


# Searching Arrays

# where()

In [ ]:
import numpy as np
arr = np.array([4,5,6,7,8])
x = np.where(arr == 6)
print(x)


(array([2]),)


# searchsorted()

In [ ]:
import numpy as np
arr = np.array([1,3,5,7])
x = np.searchsorted(arr, 4)
print(x)


2


# Sorting Arrays

In [ ]:
import numpy as np
arr = np.array([3,1,2])
print(np.sort(arr))


[1 2 3]


# Filtering Arrays

In [ ]:
import numpy as np
arr = np.array([10, 15, 20, 25])
newarr = arr[arr > 15]
print(newarr)


[20 25]


# FINAL TASK

In [ ]:
import numpy as np

arr = np.arange(2, 11).reshape(3, 3)

arr = arr.astype(float)

flat = arr.reshape(-1)

print("Matrix:\n", arr)
print("Flattened:", flat)
print("Maximum value:", np.max(flat))
print("Minimum value:", np.min(flat))


Matrix:
 [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
Flattened: [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
Maximum value: 10.0
Minimum value: 2.0
